version: "3"
services:
  activity_service_db:
    image: mongo:6.0
    container_name: service_activity_db
    ports:
      - 27017:27017
    expose:
      - "27017"
    command: mongod --dbpath /data/db --port 27017
    volumes:
      - mongodb_data:/data/db

  activity_service:
    container_name: activity_service
    build: ./src
    expose:
      - 4600
    env_file:
      - ./secrets/.env.prod
    depends_on:
      - activity_service_db
    entrypoint: sh -c "/bin/bash /opt/app/entrypoint.sh prod"
    volumes:
      - gunicorn_ugc2:/tmp

  activity_service_nginx:
    image: nginx:1.25.0
    container_name: activity_service_nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/site:/etc/nginx/conf.d:ro
      - gunicorn_ugc2:/tmp
    env_file:
      - ./secrets/.env.prod
    depends_on:
      - activity_service
    ports:
      - "4600:80"

volumes:
  mongodb_localtime:
  mongodb_data:
  gunicorn_ugc2:
