version: "3"
services:
  service_booking_postgres:
    container_name: service_booking_postgres
    image: postgres:15.0-alpine
    env_file:
      - ./secrets/.env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 5432
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  service_booking_app:
    container_name: service_booking_app
    build: ./src
    expose:
      - 4900
    env_file:
      - ./secrets/.env.prod
    entrypoint: sh -c "/bin/bash /opt/app/entrypoint.sh prod"
    depends_on:
      - service_booking_postgres
    volumes:
      - gunicorn_booking_prod:/tmp

  service_booking_nginx:
    image: nginx:1.25.0
    container_name: service_booking_nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/site:/etc/nginx/conf.d:ro
      - gunicorn_booking_prod:/tmp
      - code:/opt/app
    env_file:
      - ./secrets/.env.prod
    depends_on:
      - service_booking_app
      - service_booking_postgres
    ports:
      - "4900:80"

volumes:
  gunicorn_booking_prod:
  code:
