"""add notification state

Revision ID: 387e9169f814
Revises: 4f378a0d6846
Create Date: 2023-11-07 14:50:30.898009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387e9169f814'
down_revision: Union[str, None] = '4f378a0d6846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film_events', sa.Column('notification_state', sa.String(length=255), nullable=True), schema='booking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film_events', 'notification_state', schema='booking')
    # ### end Alembic commands ###
