version: "3"
services:
  notifications_service_rabbitmq_dev:
    container_name: notifications_service_rabbitmq_dev
    image: rabbitmq:3.10.7-management
    env_file:
      - ./secrets/.env.dev
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
