"""Database creation

Revision ID: 671e6abcf5b7
Revises:
Create Date: 2023-08-07 17:52:50.099010

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '671e6abcf5b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS content')
    op.create_table('roles',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    op.create_index(op.f('ix_content_roles_title'), 'roles', ['title'], unique=True, schema='content')
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=True),
                    sa.Column('second_name', sa.String(length=100), nullable=True),
                    sa.Column('password', sa.String(length=1000), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('is_super_user', sa.Boolean(), nullable=True),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('modified', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    op.create_index(op.f('ix_content_users_email'), 'users', ['email'], unique=True, schema='content')
    op.create_table('user_role',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('role_id', sa.UUID(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['content.roles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_users_email'), table_name='users', schema='content')
    op.drop_index(op.f('ix_content_roles_title'), table_name='roles', schema='content')
    op.drop_table('user_role', schema='content')
    op.drop_table('users', schema='content')
    op.drop_table('roles', schema='content')
    op.execute('DROP SCHEMA IF EXISTS content')
    # ### end Alembic commands ###
