"""oauth

Revision ID: 6e83eeed134e
Revises: 944601bec188
Create Date: 2023-08-25 23:01:06.085949

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e83eeed134e'
down_revision = '944601bec188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('oauth_type', postgresql.ENUM('google', name='oauthtype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'oauth_type'),
    schema='content'
    )
    op.create_index(op.f('ix_content_oauth_user_user_id'), 'oauth_user', ['user_id'], unique=False, schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_oauth_user_user_id'), table_name='oauth_user', schema='content')
    op.drop_table('oauth_user', schema='content')
    # ### end Alembic commands ###
