"""Add user history table

Revision ID: 944601bec188
Revises: f1d9413671a9
Create Date: 2023-08-12 15:18:25.587017

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '944601bec188'
down_revision = 'f1d9413671a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('operation_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('operation', postgresql.ENUM(
                        'SIGN', 'LOGIN', 'LOGOUT', 'CHANGE_PASSWORD', name='userhistoryoperation'), nullable=False
                    ),
                    sa.Column('user_agent', sa.Text(), server_default='default UA', nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history', schema='content')
    # ### end Alembic commands ###
