"""Add access tokens table

Revision ID: f1d9413671a9
Revises: 671e6abcf5b7
Create Date: 2023-08-12 13:30:04.972702

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f1d9413671a9'
down_revision = '671e6abcf5b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('user_token', sa.String(length=2000), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default='False', nullable=False),
                    sa.Column('user_agent', sa.String(length=255), server_default='default UA', nullable=False),
                    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['content.users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='content'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_tokens', schema='content')
    # ### end Alembic commands ###
