version: "3"

services:
  auth_service_postgres_dev:
    container_name: auth_service_postgres_dev
    image: postgres:15.0-alpine
    env_file:
      - ./secrets/.env.dev
    ports:
      - "5452:5432"
    volumes:
      # - ./config/backup.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
      - pg_data_dev:/var/lib/postgresql/data

  auth_service_redis_dev:
    container_name: auth_service_redis_dev
    image: redis:7.0.4-alpine
    ports:
      - "6369:6379"
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  auth_service_jaeger_dev:
    image: jaegertracing/all-in-one:latest
    container_name: auth_service_jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686/tcp"

volumes:
  pg_data_dev:
