version: "3"
services:
  service_messages_app:
    container_name: service_booking_app
    build: ./src
    expose:
      - 4800
    ports:
      - 4801:4801
    env_file:
      - ./secrets/.env.prod
    entrypoint: sh -c "/bin/bash /opt/app/entrypoint.sh prod"
    volumes:
      - gunicorn_messages_prod:/tmp

  service_messages_nginx:
    image: nginx:1.25.0
    container_name: service_booking_nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/site:/etc/nginx/conf.d:ro
      - gunicorn_messages_prod:/tmp
      - code:/opt/app
    env_file:
      - ./secrets/.env.prod
    depends_on:
      - service_messages_app
    ports:
      - "4800:80"

volumes:
  gunicorn_messages_prod:
  code:
