# Generated by Django 4.1.7 on 2023-10-13 17:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('create schema if not exists content'),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('template_title', models.CharField(max_length=255, verbose_name='Title of template')),
                ('template_text', models.TextField(verbose_name='Text of template')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'content"."template',
            },
        ),
        migrations.CreateModel(
            name='NotificationTasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('D', 'Delivered'),
                 ('Q', 'Queued'), ('C', 'Canceled')], default='Q', max_length=1)),
                ('is_broadcast', models.BooleanField(verbose_name='is Broadcast')),
                ('body', models.JSONField(verbose_name='Notification body')),
                ('importance', models.SmallIntegerField(verbose_name='Importance')),
                ('channel', models.CharField(choices=[('S', 'SMS'), ('E', 'eMail'), ('P', 'Phone')], default='E', max_length=1)),
                ('datetime_of_dispatch', models.DateTimeField(verbose_name='Time of dispatch', null=True, blank=True)),
                ('datetime_when_sended', models.DateTimeField(verbose_name='Sended at', null=True, blank=True)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.templates')),
            ],
            options={
                'verbose_name': 'Notification task',
                'verbose_name_plural': 'Notification tasks',
                'db_table': 'content"."notificationtask',
            },
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(verbose_name='User ID')),
                ('status', models.CharField(choices=[('D', 'Delivered'),
                 ('E', 'Error'), ('I', 'Initiated'), ('R', 'Readed')], default='I', max_length=1)),
                ('notification_tasks_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.notificationtasks')),
            ],
            options={
                'verbose_name': 'Notification status',
                'verbose_name_plural': 'Notification statuses',
                'db_table': 'content"."notificationstatus',
            },
        ),
    ]
